### ISSUE TITLE
Is the 1.2.0 release planned?

### ISSUE THREAD

**Issue by jozuas** [dbernheisel/date_time_parser#11]
Is the 1.2.0 release planned?

The 1.1.5 release contains a requirement for the max Timex dependency version of 3.7.2, which is pretty old.

![image](https://github.com/dbernheisel/date_time_parser/assets/13085275/727cad02-0825-4526-886d-7bb9bcacfa2f)

If there's a clear list of things todo, perhaps you need help to make 1.2.0 possible?

**Comment by dbernheisel** [comment]
I've sat on it long enough :) I'll get one one today.

**Comment by dbernheisel** [comment]
Released 1.2.0 
Please give it a go and let me know how it goes

**Comment by jozuas** [comment]
I have not run into any issues, thanks a lot for your work 🙂
