### ISSUE TITLE
Timex dependency excludes latest versions

### ISSUE THREAD

**Issue by deepankar-j** [dbernheisel/date_time_parser#9]
The dependency of timex >= 3.2.1 and <= 3.7.2 prevents my app from being able to upgrade timex to the latest version.  Could you please update the dependency to allow the latest version of times, 3.7.11?

**Comment by dbernheisel** [comment]
Duplicate of #5

**Comment by dbernheisel** [comment]
Can you try the main branch and see if that helps? It drops the Timex dependency.

**Comment by dbernheisel** [comment]
This has been released in 1.2.0
